apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests.yaml
namespace: default
labels:
  - pairs:
      test.label: hello-world4
    includeTemplates: true
commonLabels:
  app: ben-test-podinfo
