---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: app-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ben-test-podinfo
spec:
  template:
    metadata:
      labels: #https://github.com/kubernetes-sigs/kustomize/issues/4717, outstanding bug
    spec:
      containers:
        - name: running-pod
          image: ben-test-podinfo
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
