name: Automerge flux image updates
on:
  push:
    branches:
    - flux-dev-*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        pr_title: Automerge flux dev image update
        pr_label: "flux-auto-pr" 
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/peter-evans/enable-pull-request-automerge
# https://github.com/marketplace/actions/create-pull-request
# https://github.com/marketplace/actions/github-pull-request-action