name: Automerge flux image updates
on:
  push:
    branches:
    - flux-dev-*

jobs:
  pull-request-auto-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get image name from branch
      run:
        IMAGE_NAME="${GITHUB_REF##*/}" && IMAGE_NAME=${IMAGE_NAME:9} && echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_ENV"
    - name: pull-request
      id: cpr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.REPO_PAT_CAISLEAR }}
        pr_title: "Automerge flux dev image: ${IMAGE_NAME}"
        pr_label: "flux-auto-pr" 
        pr_reviewer: "Caislear"
        destination_branch: "main"
    - name: Enable Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.REPO_PAT_CAISLEAR }}
        pull-request-number: ${{ steps.cpr.outputs.pr_number }}
        merge-method: squash
    # condition to check that there is only one commit on this branch by specific user only
    - name: Auto approve PR
      uses: juliangruber/approve-pull-request-action@v2
      with:
        github-token: ${{ secrets.secrets.GITHUB_TOKEN }}
        number: ${{ steps.cpr.outputs.pr_number }}

# https://github.com/peter-evans/enable-pull-request-automerge
# https://github.com/marketplace/actions/create-pull-request
# https://github.com/marketplace/actions/github-pull-request-action