name: Flux create and automerge dev prs
on:
  push:
    branches:
    - flux-dev-*

jobs:
  pull-request-auto-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get image name from branch
      run:
        IMAGE_NAME="${GITHUB_REF##*/}" && IMAGE_NAME=${IMAGE_NAME:9} && echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_ENV"
    - name: Create pull-request
      id: cpr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.REPO_PAT_CAISLEAR }}
        pr_title: "Automerge flux dev image: ${{ env.IMAGE_NAME }}"
        pr_label: "flux-auto-pr" 
        destination_branch: "main"
    - name: Enable automerge
      uses: reitermarkus/automerge@v2.2.0
      with:
        token: ${{ secrets.REPO_PAT_CAISLEAR }}
        merge-method: squash
        required-labels: flux-auto-pr
        squash-commit-title: ${pull_request.title}
        pull-request: ${{ steps.cpr.outputs.pr_number }}
    # condition to check that there is only one commit on this branch by specific user only
    - name: Auto approve PR
      uses: juliangruber/approve-pull-request-action@v2.0.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.cpr.outputs.pr_number }}

# https://github.com/peter-evans/enable-pull-request-automerge
# https://github.com/marketplace/actions/create-pull-request
# https://github.com/marketplace/actions/github-pull-request-action