name: terraform-lint
on:
  pull_request:
jobs:
  fmt:
    name: terraform-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check format
        # if: !"contains('refs/heads/flux-', github.ref)"
        run: terraform fmt -check -recursive

