name: terraform-lint
on:
  pull_request:
jobs:
  fmt:
    #if: "!contains('refs/heads/flux-', github.ref)"
    name: terraform-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check format 
        run: terraform fmt -check -recursive

