name: terraform-lint
on:
  push:
    branches:
    - flux-dev-*
    - main
  pull_request:
jobs:
  check-for-flux:
    name: Check if Flux branch
    runs-on: ubuntu-latest
    outputs: 
      is_flux_branch: ${{ steps.check-for-flux.outputs.STATUS }}
    steps:
      - name: Flux branch test
        id: check-for-flux
        env:
          FLUX_STRING: 'flux-'
          TEST_CONDITION: ${{ startsWith( (github.head_ref || github.ref_name) , 'flux-') }}
        run: |-
          echo "head_ref: ${GITHUB_HEAD_REF:0:5}" && echo "ref_name: ${GITHUB_REF_NAME:0:5}"
          ([[ ${GITHUB_HEAD_REF:0:5} == "$FLUX_STRING" ]] || [[ ${GITHUB_REF_NAME:0:5} == "$FLUX_STRING" ]]) && IS=true || IS=false
          echo $TEST_CONDITION
          echo STATUS=$IS >> $GITHUB_OUTPUT

  output-status-check:
    needs: check-for-flux
    name: output-status
    runs-on: ubuntu-latest
    steps:
      - name: output
        env: 
          OUTPUT: ${{ needs.check-for-flux.outputs.is_flux_branch }}
        run: echo $OUTPUT
  terraform-lint:
    needs: check-for-flux
    if: needs.check-for-flux.outputs.is_flux_branch == 'false'
    name: terraform-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check format 
        run: terraform fmt -check -recursive
      - name: Attmempt env output
        run: env
      - name: Attempt echo of github ref
        run: echo $GITHUB_REF
      - name: Attempt echo of github ref_name
        run: echo $GITHUB_REF_NAME

