name: terraform-lint
on:
  pull_request:
    types: [opened, reopened]
jobs:
  terraform-lint:
    if: "!startsWith(github.ref_name, 'flux-')"
    name: terraform-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check format 
        run: terraform fmt -check -recursive
      - name: Wait
        run: sleep 10000

