apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ben-test-podinfo
images:
  - name: job-monitor
    newName: temp # {"$imagepolicy": "flux-system:ben-test-podinfo:name"}
    newTag: temp # {"$imagepolicy": "flux-system:ben-test-podinfo:tag"}
