apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ben-test-podinfo
images:
  - name: ben-test-podinfo
    newName: europe-west3-docker.pkg.dev/y42-artifacts-ea47981a/test/ben-test-podinfo # {"$imagepolicy": "flux-system:ben-test-podinfo:name"}
    newTag: 968f3d4-2022111009 # {"$imagepolicy": "flux-system:ben-test-podinfo:tag"}
