apiVersion: v1
kind: Namespace
metadata:
  name: app-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-podinfo
spec:
  template:
    metadata:
      labels: #https://github.com/kubernetes-sigs/kustomize/issues/4717, outstanding bug
    spec:
      containers:
        - name: running-pod
          image: europe-west3-docker.pkg.dev/y42-artifacts-ea47981a/test/ben-test-podinfo:968f3d4-202211100913 # {"$imagepolicy": "flux-system:ben-test-podinfo"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
